services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: led-calculator-backend
    container_name: led-calculator-backend-container
    env_file:
      - ./backend/.env
    networks:
      - led-calculator-network
    restart: unless-stopped

networks:
  led-calculator-network:
    driver: bridge