services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
    - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ./backend  # <-- изменил путь
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: "7d"
      BCRYPT_SALT: "10"
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/prisma/migrations

  frontend:
    build:
      context: ./frontend  # <-- изменил путь
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pg_data:
  backend_data: